language: php
sudo: false
php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2

# Define an environment variable
env:
  - SYMFONY_VERSION="3.2.*" DB=mysql

services:
  - mysql

before_script:
  - cp app/config/parameters.yml.dist app/config/parameters.yml
  - composer self-update
  - composer install --dev --no-interaction --prefer-source
  - app/console doctrine:database:create --env=test --no-interaction --quiet
  - app/console doctrine:migrations:migrate --env=test --no-interaction --quiet
  - app/console cache:warmup --env=test --quiet

script:
  - ./bin/phpspec run -fpretty --verbose
  - ./bin/behat  --no-snippets --no-paths --verbose

notifications:
  email:
    on_success: change  # options: [always|never|change] default: always
    on_failure: change  # options: [always|never|change] default: always