language: php
sudo: false
php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2

# Define an environment variable
env:
  - SYMFONY_VERSION="3.2.*" DB=mysql

services:
  - mysql

# Update composer
before-install:
  - composer self-update

before_script:
  - cp app/config/parameters.yml.dist app/config/parameters.yml
  - composer self-update
  - composer install --dev --no-interaction --prefer-source
  - app/console doctrine:database:create --env=test --no-interaction --quiet
  - app/console doctrine:migrations:migrate --env=test --no-interaction --quiet
  - app/console cache:warmup --env=test --quiet

# Install composer dependencies,
# Create database, schema and fixtures
install:
  - composer install
  - cp app/config/parameters.yml.dist app/config/parameters.yml
  - php bin/console doctrine:database:create --env=test
  - php bin/console doctrine:schema:create --env=test
  - php bin/console doctrine:fixtures:load -n --env=test

# Run script
script:
  - ./bin/phpspec run -fpretty --verbose
  - ./bin/behat  --no-snippets --no-paths --verbose
  - ./vendor/bin/phpunit

notifications:
  email:
    on_success: change  # options: [always|never|change] default: always
    on_failure: change  # options: [always|never|change] default: always