iot_boiler_view_only:
    resource: "@IotBundle/Controller/BoilerViewOnlyController.php"
    type:     annotation

iot_test:
    resource: "@IotBundle/Controller/TestController.php"
    type:     annotation

iot_device_model:
    resource: "@IotBundle/Controller/DeviceModelController.php"
    type:     annotation

iot_device_model:
    resource: "@IotBundle/Controller/DeviceModelController.php"
    type:     annotation

iot_device_model:
    resource: "@IotBundle/Controller/DeviceModelController.php"
    type:     annotation

iot_device:
    resource: "@IotBundle/Controller/DeviceController.php"
    type:     annotation

iot_device:
    resource: "@IotBundle/Controller/DeviceController.php"
    type:     annotation

iot_device:
    resource: "@IotBundle/Controller/DeviceController.php"
    type:     annotation

tester_target:
    resource: "@TesterBundle/Controller/TargetController.php"
    type:     annotation

tester_skip_mode:
    resource: "@TesterBundle/Controller/SkipModeController.php"
    type:     annotation

tester_response:
    resource: "@TesterBundle/Controller/ResponseController.php"
    type:     annotation

tester_prompt_state:
    resource: "@TesterBundle/Controller/PromptStateController.php"
    type:     annotation

tester_os_state:
    resource: "@TesterBundle/Controller/OsStateController.php"
    type:     annotation

tester_action_verdict:
    resource: "@TesterBundle/Controller/ActionVerdictController.php"
    type:     annotation

tester_action:
    resource: "@TesterBundle/Controller/ActionController.php"
    type:     annotation
iot:
    resource: "@IotBundle/Resources/config/routing.xml"
    prefix:   /iot

tester:
    resource: "@TesterBundle/Resources/config/routing.xml"
    prefix:   /tester

werd_finance_stock_data:
    resource: "@WerdFinanceBundle/Controller/StockDataController.php"
    type:     annotation

werd_finance_company:
    resource: "@WerdFinanceBundle/Controller/CompanyController.php"
    type:     annotation

werd_finance:
    resource: "@WerdFinanceBundle/Resources/config/routing.php"
    prefix:   /finance

app:
    resource: "@AppBundle/Controller/"
    prefix:   /
