<?php

namespace Werd\FinanceBundle\Repository;

/**
 * StockDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StockDataRepository extends \Doctrine\ORM\EntityRepository
{
}
