<?php

namespace WerdGameBundle\Repository;

/**
 * DELResourceBaseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DELResourceBaseRepository extends \Doctrine\ORM\EntityRepository
{
}
