<?php

namespace WerdGameBundle\Repository;

/**
 * MineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MineRepository extends \Doctrine\ORM\EntityRepository
{
}
