<?php

namespace WerdGameBundle\Repository;

/**
 * ResourceRawMaterialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResourceRawMaterialRepository extends \Doctrine\ORM\EntityRepository
{
}
