<?php

namespace WerdGameBundle\Repository;

/**
 * TypeHeroRaceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeHeroRaceRepository extends \Doctrine\ORM\EntityRepository
{
}
