<?php

namespace WerdGameBundle\Repository;

/**
 * TypeHeroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeHeroRepository extends \Doctrine\ORM\EntityRepository
{
}
