<?php

namespace Werd\TesterBundle\Repository;

/**
 * ActionVerdictRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActionVerdictRepository extends \Doctrine\ORM\EntityRepository
{
}
