<?php

namespace Werd\TesterBundle\Repository;

/**
 * OsStateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OsStateRepository extends \Doctrine\ORM\EntityRepository
{
}
