<?php

namespace Werd\TesterBundle\Repository;

/**
 * PromptStateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PromptStateRepository extends \Doctrine\ORM\EntityRepository
{
}
