<?php

namespace Werd\TesterBundle\Repository;

/**
 * SkipModeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SkipModeRepository extends \Doctrine\ORM\EntityRepository
{
}
