<?php

namespace Werd\IotBundle\Repository;

/**
 * BoilerViewOnlyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BoilerViewOnlyRepository extends \Doctrine\ORM\EntityRepository
{
}
