<?php

namespace Werd\IotBundle\Repository;

/**
 * DeviceModelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeviceModelRepository extends \Doctrine\ORM\EntityRepository
{
}
